"use client";

import { useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { ChatGPTLogo } from "../components/ModelLogos";

type Lang = "en" | "es";

const copy = {
  en: {
    menu: "Menu",
    title: "ChatGPT analysis",
    placeholder: "Analysis generated by ChatGPT on the path to becoming a tax preparer will go here. Content pending.",
  },
  es: {
    menu: "Menú",
    title: "Análisis de ChatGPT",
    placeholder: "Aquí irá el análisis generado por ChatGPT sobre la ruta para ser preparador de impuestos. Contenido pendiente de añadir.",
  },
};

export default function AnalisisChatGPTPage() {
  const [lang, setLang] = useState<Lang>("en");
  const t = copy[lang];

  return (
    <div className="min-h-screen bg-neutral-950 text-neutral-100">
      <div className="pointer-events-none fixed inset-0 -z-10 overflow-hidden">
        <div className="absolute left-1/2 top-[-180px] h-[480px] w-[480px] -translate-x-1/2 rounded-full bg-emerald-500/15 blur-3xl" />
      </div>

      <header className="sticky top-0 z-50 border-b border-white/10 bg-neutral-950/70 backdrop-blur">
        <div className="mx-auto flex max-w-4xl items-center justify-between px-4 py-4">
          <Link
            href="/"
            className="rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm font-medium text-neutral-300 transition hover:bg-white/10 hover:text-white"
          >
            ← {t.menu}
          </Link>
          <div className="flex items-center gap-2">
            <ChatGPTLogo size={32} />
            <span className="hidden text-sm font-semibold sm:inline">{t.title}</span>
            <button
              onClick={() => setLang((p) => (p === "en" ? "es" : "en"))}
              className="rounded-full border border-white/10 bg-white/5 px-2.5 py-1.5 text-xs font-medium text-neutral-300 transition hover:bg-white/10"
              aria-label={lang === "en" ? "Switch to Spanish" : "Cambiar a inglés"}
            >
              {lang === "en" ? "ES" : "EN"}
            </button>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-4 pb-24 pt-12" data-readaloud-content>
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.35 }}
          className="rounded-3xl border border-emerald-500/20 bg-white/5 p-8"
        >
          <div className="flex flex-col items-center justify-center gap-6 text-center">
            <div className="rounded-2xl bg-gradient-to-br from-emerald-500/20 to-teal-600/20 p-6">
              <ChatGPTLogo />
            </div>
            <h1 className="text-2xl font-bold">{t.title}</h1>
            <p className="max-w-lg text-neutral-400">
              {t.placeholder}
            </p>
          </div>
        </motion.div>
      </main>
    </div>
  );
}
